apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: prc-pvc
 labels:
   eidf/user: $USER
spec:
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 250Gi
 storageClassName: csi-cephfs-sc